### ISSUE TITLE
Review from Yang Ge

### ISSUE THREAD

**Issue by ygechn** [epid8060fall2019/William-Norfolk-Project#3]
Hello William.

Well done. Because I don't know Ecology, so mainly comment on the format. Here are my comments.

1. The title of Figure 1 was not right.
2. Because your figure results may have round number issue, violin plots may not better then boxplot
3. I didn't find some test on results, I thought:
“Question 4: Citizen Science Data Efficacy
Is citizen science data accurate enough to capture large-scale environmental trends and is the data specific enough to characterize different aquatic habitat types."
This question could have some test and p-value on the comparison.

**Comment by williamnorfolk** [comment]
Hi Yang Ge,

Thank you for your feedback! I appreciate the ideas, I will be sure to address them before the final date. Just a heads up you need to complete the peer review using Dr. Handel's review template using the fork and pull method (the details are on the course website under project reviews)! I will be happy to merge the review Rmd once you are done!

William

**Comment by ygechn** [comment]
Thanks
